import { ArrowLeft, ArrowRight, Check, Eye, EyeOff, Sparkles } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Button } from '../components/ui'
import { useApp } from '../state/AppContext'

export function AuthPage({ mode }: { mode: 'login' | 'signup' }) {
  const { login, signup } = useApp(); const nav = useNavigate(); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setError(''); setLoading(true); const data = new FormData(e.currentTarget); const result = mode === 'login' ? await login(String(data.get('email')), String(data.get('password'))) : await signup(String(data.get('name')), String(data.get('email')), String(data.get('password'))); setLoading(false); if (!result.ok) return setError(result.error); nav(mode === 'signup' ? '/diagnostic' : '/app') }
  return <div className="auth-page"><div className="auth-panel"><Link to="/" className="brand"><span className="brand-mark"><Sparkles size={20}/></span><span>MadeByAibek</span></Link><Link to="/" className="back-link"><ArrowLeft size={15}/> Back to home</Link><div className="auth-copy"><span className="eyebrow">{mode === 'login' ? 'Welcome back' : 'Your learning starts here'}</span><h1>{mode === 'login' ? 'Continue building your English.' : 'English practice, shaped around you.'}</h1><p>{mode === 'login' ? 'Pick up exactly where you left off.' : 'Start with a focused diagnostic and get a plan based on your real strengths and gaps.'}</p>{mode === 'signup' && <ul><li><Check/>Personal skill profile</li><li><Check/>Adaptive recommendations</li><li><Check/>Clear, useful feedback</li></ul>}</div><blockquote>“The first platform that showed me exactly <em>why</em> I kept losing marks.”<footer><span>AS</span><div><strong>Amir S.</strong><small>IELTS learner · B2 → C1</small></div></footer></blockquote></div>
    <div className="auth-form-wrap"><form onSubmit={submit}><div><span className="eyebrow">{mode === 'login' ? 'Sign in' : 'Create account'}</span><h2>{mode === 'login' ? 'Good to see you again.' : 'Let’s build your profile.'}</h2><p>{mode === 'login' ? <>New to MadeByAibek? <Link to="/signup">Create an account</Link></> : <>Already have an account? <Link to="/login">Log in</Link></>}</p></div>{mode === 'signup' && <label>First name<input name="name" required minLength={2} placeholder="Maya"/></label>}<label>Email address<input name="email" required type="email" placeholder="you@example.com" defaultValue={mode==='login'?'maya@lexora.demo':''}/></label><label>Password<div className="password-input"><input name="password" required minLength={mode==='signup'?8:1} type={show?'text':'password'} placeholder="At least 8 characters" defaultValue={mode==='login'?'lexora':''}/><button type="button" onClick={()=>setShow(!show)} aria-label="Show password">{show?<EyeOff/>:<Eye/>}</button></div></label>{error && <div className="form-error">{error}</div>}<Button loading={loading} type="submit">{mode === 'login' ? 'Log in' : 'Create my account'} <ArrowRight size={16}/></Button>{mode === 'login' && <Link className="forgot" to="/password-reset">Forgot password?</Link>}<small className="terms">By continuing, you agree to our Terms and Privacy Policy.</small></form></div></div>
}
