import { ArrowRight, BookOpen, BrainCircuit, CheckCircle2, ChevronRight, Clock3, Flame, Sparkles, Target, TrendingUp, Zap } from 'lucide-react'
import { Link } from 'react-router-dom'
import { ArrowLink, Badge, Button, Card, EmptyState, ProgressBar, SectionHeading } from '../components/ui'
import { useApp } from '../state/AppContext'

export function DashboardPage() {
  const { user, recommendation:serverRecommendation } = useApp(); if (!user) return null
  const dailyGoal=user.dailyGoal??15
  const today=new Date(), todayLabel=today.toLocaleDateString('en-US',{weekday:'long',day:'numeric',month:'long'}).toUpperCase(), nextLevel=user.level==='C1'?'C2':user.level==='B2'?'C1':user.level.startsWith('B1')?'B2':'B1'
  const weekDays=(user.weeklyActivity??user.weeklyMinutes.map((minutes,index)=>{const date=new Date(today);date.setDate(today.getDate()-(6-index));return{date:date.toISOString().slice(0,10),minutes,xp:0}})).map((day,index)=>({label:new Date(`${day.date}T12:00:00`).toLocaleDateString('en-US',{weekday:'narrow'}),minutes:day.minutes,isToday:index===6}))
  const measuredSkills=user.skills.filter(skill=>skill.assessed); const hasMeasurements=measuredSkills.length>0
  const weakest = [...(hasMeasurements?measuredSkills:user.skills)].sort((a,b)=>a.score-b.score).slice(0,3)
  const nextBySkill:Record<string,{title:string;path:string;meta:string}>={complexGrammar:{title:'Mixed conditional sentences',path:'/app/complex-grammar',meta:'10 questions · ~7 min'},writing:{title:'Sentence accuracy and coherence',path:'/app/essay',meta:'Essay feedback · ~10 min'},vocabulary:{title:'Academic vocabulary review',path:'/app/vocabulary',meta:'8 words · ~6 min'},reading:{title:'Reading inference',path:'/app/reading',meta:'15 passages · ~8 min each'},grammar:{title:'Articles in context',path:'/app/grammar',meta:'10 questions · ~7 min'},mainIdeas:{title:'Central idea summaries',path:'/app/main-ideas',meta:'15 passages · two response modes'},integratedSummary:{title:'Integrated skills summary',path:'/app/integrated-summary',meta:'Academic text · 150–250 words'}}
  const recommended=nextBySkill[serverRecommendation?.skill??weakest[0]?.key??'grammar']??nextBySkill.grammar; const recommendationPath=hasMeasurements?recommended.path:'/diagnostic'
  return <div className="dashboard page-enter">
    <div className="page-welcome"><div><span className="eyebrow">{todayLabel}</span><h1>Good morning, {user.name}.</h1><p>Here’s where your English stands—and what to focus on next.</p></div><div className="welcome-streak"><Flame/><div><strong>{user.streak} days</strong><span>Current streak</span></div></div></div>
    <div className="dashboard-lead">
      <Card className="level-card"><div><span className="card-label">CURRENT ENGLISH LEVEL</span><div className="large-level">{user.level.replace('+','')}<sup>{user.level.includes('+')?'+':''}</sup></div><Badge tone={hasMeasurements?'green':'neutral'}><TrendingUp size={12}/> {hasMeasurements?'Measured profile':'Not assessed'}</Badge></div><div className="level-progress"><div><span>Overall measured mastery</span><strong>{hasMeasurements?`${user.levelProgress}%`:'—'}</strong></div><ProgressBar value={hasMeasurements?user.levelProgress:0}/><p>{hasMeasurements?`This is the average of your assessed skills and updates after recorded practice.`:'Complete the diagnostic or a practice session to create your skill baseline.'}</p></div><div className="level-rings"><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="49"/><circle className="active" cx="60" cy="60" r="49" style={{strokeDashoffset:308-(308*(hasMeasurements?user.levelProgress:0)/100)}}/><text x="60" y="58">{hasMeasurements?`${user.levelProgress}%`:'—'}</text><text x="60" y="76">{hasMeasurements?'MEASURED':'NO DATA'}</text></svg></div></Card>
      <Card className="daily-card"><div className="card-title"><span className="card-label">DAILY GOAL</span><CheckCircle2/></div><div className="daily-time"><strong>{user.dailyMinutes}</strong><span>/ {dailyGoal} min</span></div><ProgressBar value={Math.min(100,user.dailyMinutes/dailyGoal*100)}/><p>{user.dailyMinutes >= dailyGoal ? 'Goal complete. Excellent consistency.' : `${dailyGoal-user.dailyMinutes} minutes left. One short lesson will do it.`}</p><div className="week-dots">{weekDays.map((day,index)=><div key={index}><span className={day.minutes>0?'done':day.isToday?'today':''}>{day.minutes>0?<CheckCircle2/>:day.label}</span><small>{day.label}</small></div>)}</div></Card>
    </div>
    <div className="dash-grid">
      <Card className="recommend-card"><div className="recommend-copy"><Badge tone="amber"><Sparkles size={12}/> Recommended next</Badge><span className="card-label">{hasMeasurements?(serverRecommendation?.skill??weakest[0]?.label).toUpperCase():'BUILD YOUR BASELINE'} · ADAPTIVE</span><h2>{serverRecommendation?.title??recommended.title}</h2><p>{serverRecommendation?.reason??(hasMeasurements?`${weakest[0].label} is currently your lowest measured skill at ${weakest[0].score}%.`:'Complete the diagnostic to create a measured skill profile.')}</p><div className="session-meta"><span><BookOpen size={15}/> {hasMeasurements?recommended.meta.split(' · ')[0]:'6 questions'}</span><span><Clock3 size={15}/> {hasMeasurements?recommended.meta.split(' · ')[1]:'~7 min'}</span><span><Zap size={15}/> Recorded results</span></div><Link to={recommendationPath}><Button>{hasMeasurements?'Continue practice':'Take diagnostic'} <ArrowRight size={16}/></Button></Link></div><div className="recommend-visual"><div className="syntax"><span>{hasMeasurements?<>Focus on <u>{weakest[0].label}</u></>:<>Start with a <u>measured baseline</u></>}</span><i></i><span>Build toward <u>{nextLevel} accuracy</u>.</span></div><BrainCircuit/></div></Card>
      <Card className="weak-card"><SectionHeading eyebrow="Focus areas" title={hasMeasurements?'Your weakest skills':'Skills to measure'}/><div className="weak-list">{weakest.map((s,i)=><div key={s.key}><span className="weak-rank">0{i+1}</span><div><strong>{s.label}</strong><small>{hasMeasurements?(i===0?'Priority focus':i===1?'Needs attention':'Keep building'):'No result yet'}</small></div><span className="weak-score">{hasMeasurements?`${s.score}%`:'—'}</span><ChevronRight/></div>)}</div><Link to={hasMeasurements?'/app/progress':'/diagnostic'}><ArrowLink>{hasMeasurements?'View full analysis':'Take diagnostic'}</ArrowLink></Link></Card>
    </div>
    <SectionHeading eyebrow="Your skill profile" title="A clear view of every skill" action={<Link to="/app/progress"><ArrowLink>View progress</ArrowLink></Link>}/>
    <div className="skill-grid">{user.skills.map((s,i)=><Card className="skill-card" key={s.key}><div className="skill-icon" style={{background:`${s.color}18`,color:s.color}}>{i===0?<BookOpen/>:i===1?<BrainCircuit/>:i===2?<Sparkles/>:i===3?<Target/>:i===4?<Zap/>:<Target/>}</div><div className="skill-score"><strong>{s.assessed?s.score:'—'}{s.assessed&&<sup>%</sup>}</strong><span className={s.delta>0?'positive':''}>{s.assessed&&s.attempts?`${s.delta>=0?'+':''}${s.delta}%`:'—'}</span></div><h3>{s.label}</h3><ProgressBar value={s.assessed?s.score:0} color={s.color}/><small>{!s.assessed?'Not assessed':s.score<55?'Needs focused practice':s.score<70?'Building steadily':'Strong and improving'}</small></Card>)}</div>
    <div className="activity-row"><Card className="recent-card"><SectionHeading eyebrow="Recent work" title="Latest activity"/>{user.activities.length?user.activities.map(a=><div className="activity-item" key={a.id}><div className="activity-icon"><BookOpen/></div><div><strong>{a.title}</strong><span>{a.kind} · {a.date}</span></div><div className="activity-score"><strong>{a.score}%</strong><small>+{a.xp} XP</small></div></div>):<EmptyState icon={<BookOpen/>} title="No practice yet" description="Complete your first recommended session to start building a progress history."/>}</Card><Card className="xp-card"><Zap/><span className="card-label">LAST 7 DAYS</span><strong>+{user.weeklyXp??0} XP</strong><p>{(user.weeklyXp??0)>0?'Every completed session is building your level profile.':'Complete a session to start this week’s progress.'}</p><div className="xp-bars">{weekDays.map((day,i)=><span key={i} style={{height:`${Math.max(6,Math.min(100,day.minutes/45*100))}%`}} className={day.minutes===Math.max(...weekDays.map(item=>item.minutes))&&day.minutes>0?'hot':''}/>)}</div></Card></div>
  </div>
}
