import { ArrowLeft, ArrowRight, Check, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { Navigate, useNavigate } from 'react-router-dom'
import { Button, ProgressBar } from '../components/ui'
import { diagnosticQuestions } from '../data/seed'
import { useApp } from '../state/AppContext'

export function DiagnosticPage() {
  const { user, completeDiagnostic } = useApp(); const nav = useNavigate(); const [started, setStarted] = useState(false); const [index, setIndex] = useState(0); const [answers, setAnswers] = useState<number[]>([]); const [choice, setChoice] = useState<number|null>(null); const [done,setDone] = useState(false)
  const pairScore=(indexes:number[])=>Math.round(indexes.filter(i=>answers[i]===diagnosticQuestions[i]?.answer).length/indexes.length*100)
  const resultScores={grammar:pairScore([0,1]),complexGrammar:pairScore([2,8]),vocabulary:pairScore([3,9]),mainIdeas:pairScore([4,10]),reading:pairScore([5,11]),writing:pairScore([6,7])}
  if (!user) return <Navigate to="/signup" replace/>
  if (!started) return <div className="diagnostic-intro"><div className="diagnostic-logo"><Sparkles/></div><span className="eyebrow">Your starting point</span><h1>Let’s find the right level for you.</h1><p>Answer {diagnosticQuestions.length} varied questions. We’ll use your responses to create a first skill profile—no grades, no pressure.</p><div className="diagnostic-facts"><div><strong>{diagnosticQuestions.length}</strong><span>questions</span></div><div><strong>~10</strong><span>minutes</span></div><div><strong>6</strong><span>skills mapped</span></div></div><Button onClick={()=>setStarted(true)}>Start diagnostic <ArrowRight size={17}/></Button><button className="text-button" onClick={()=>nav('/app')}>Skip for now</button></div>
  if (done) { const correct = answers.filter((a,i)=>a===diagnosticQuestions[i].answer).length; const accuracy=correct/diagnosticQuestions.length; const estimatedLevel=accuracy>=.8?'B2':accuracy>=.5?'B1+':'B1'; const rows=[['Grammar',resultScores.grammar],['Vocabulary',resultScores.vocabulary],['Reading',resultScores.reading],['Writing',resultScores.writing],['Complex grammar',resultScores.complexGrammar],['Main ideas',resultScores.mainIdeas]] as const; const weakest=[...rows].sort((a,b)=>a[1]-b[1])[0][0]; return <div className="diagnostic-result"><div className="confetti-mark"><Check/></div><span className="eyebrow">Diagnostic complete</span><h1>Your estimated level is <em>{estimatedLevel}</em></h1><p>Your answers show that <strong>{weakest.toLowerCase()}</strong> should be your first focus. Your plan will adapt as you complete more practice.</p><div className="diagnostic-scores">{rows.map(([x,v])=><div key={x}><span>{x}</span><ProgressBar value={v}/><strong>{v}%</strong></div>)}</div><Button onClick={async()=>{ await completeDiagnostic(resultScores); nav('/app') }}>View my learning plan <ArrowRight size={17}/></Button></div> }
  const current = diagnosticQuestions[index]; const next = () => { if(choice===null)return; const updated=[...answers,choice]; setAnswers(updated); setChoice(null); if(index===diagnosticQuestions.length-1)setDone(true);else setIndex(index+1) }
  return <div className="diagnostic-player"><header><button onClick={()=>index ? setIndex(index-1) : setStarted(false)}><ArrowLeft/></button><LinkBrand/><span>{index+1} of {diagnosticQuestions.length}</span></header><ProgressBar value={(index+1)/diagnosticQuestions.length*100}/><main><span className="eyebrow">{current.skill} · {current.level}</span>{current.context && <section className="diagnostic-context"><span>Read the passage</span><p>{current.context}</p></section>}<h1>{current.prompt}</h1><div className="diagnostic-options">{current.options.map((o,i)=><button key={o} onClick={()=>setChoice(i)} className={choice===i?'selected':''}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}</div><Button disabled={choice===null} onClick={next}>{index===diagnosticQuestions.length-1?'Finish diagnostic':'Next question'} <ArrowRight size={16}/></Button></main></div>
}
function LinkBrand(){return <div className="brand"><span className="brand-mark"><Sparkles size={18}/></span><span>MadeByAibek</span></div>}
