import { AlertCircle, ArrowRight, CheckCircle2, FilePenLine, LoaderCircle, RotateCcw, ShieldCheck, Sparkles, WandSparkles } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { Badge, Button, Card, ProgressBar } from '../components/ui'
import { aiService } from '../services/ai'
import type { EssayAnalysis } from '../types'
import { useApp } from '../state/AppContext'
import { api } from '../services/api'
import type { EssayRecord } from '../types'

const sample='Technology has changed the way we study and work. People is becoming more dependent on digital tools, and this show both benefits and risks. Students can find informations quickly, but they may depend of technology too much. In my view, schools should teach learners how to use these tools thoughtfully. This approach would help people gain the benefits while still developing independent thinking and strong communication skills.'
export function EssayPage() {
  const [text,setText]=useState(''); const [prompt,setPrompt]=useState(''); const [loading,setLoading]=useState(false); const [result,setResult]=useState<EssayAnalysis|null>(null); const [error,setError]=useState(''); const [history,setHistory]=useState<EssayRecord[]>([]); const {recordActivity}=useApp(); const startedAt=useRef(Date.now())
  useEffect(()=>{api.essays().then(r=>setHistory(r.essays)).catch(()=>setHistory([]))},[])
  const analyze=async()=>{setLoading(true);setError('');try{const r=await aiService.analyzeEssay(text,prompt);setResult(r);await recordActivity({kind:'Essay',title:prompt||'Essay analysis',score:Math.round(r.overall/9*100),xp:60,mistakes:r.patterns,durationSeconds:Math.max(1,Math.round((Date.now()-startedAt.current)/1000))},'writing');const latest=await api.essays();setHistory(latest.essays)}catch(e){setError(e instanceof Error?e.message:'Analysis failed. Please try again.')}finally{setLoading(false)}}
  if(result){const band=result.overall>=8?'C1':result.overall>=7?'B2':result.overall>=5.5?'B1':'Developing';return <div className="essay-results page-enter"><div className="results-head"><div><Badge tone="green"><CheckCircle2 size={12}/> Analysis complete</Badge><h1>Your essay feedback</h1><p>Feedback is grouped by pattern so you can turn corrections into progress.</p></div><Button variant="secondary" onClick={()=>setResult(null)}><RotateCcw size={15}/> Check another essay</Button></div><div className="essay-score-grid"><Card className="overall-score"><span>Overall score</span><strong>{result.overall}</strong><small>out of 9.0</small><Badge tone="green">Estimated {band}</Badge></Card>{Object.entries(result.scores).map(([k,v])=><Card key={k}><span>{k.replace(/([A-Z])/g,' $1')}</span><strong>{v}</strong><ProgressBar value={v/9*100}/><small>{v>=7?'Strong performance':v>=6.5?'Developing well':'Priority area'}</small></Card>)}</div><div className="essay-feedback-grid"><Card><span className="eyebrow">SUMMARY</span><h2>What stands out</h2><p>{result.summary}</p><div className="strengths">{result.strengths.map(x=><span key={x}><CheckCircle2/>{x}</span>)}</div></Card><Card><span className="eyebrow">RECURRING PATTERNS</span><h2>Turn feedback into practice</h2>{result.patterns.map((x,i)=><div className="pattern-row" key={x}><span>0{i+1}</span><div><strong>{x}</strong><small>Detected in this essay</small></div><ArrowRight/></div>)}</Card></div><Card className="corrections"><span className="eyebrow">LANGUAGE CORRECTIONS</span><h2>Review individual errors</h2>{result.errors.map((e,i)=><div className="correction" key={i}><Badge tone="amber">{e.type}</Badge><div className="correction-text"><del>{e.original}</del><ArrowRight/><ins>{e.correction}</ins></div><p>{e.explanation}</p></div>)}</Card></div>}
  return <div className="essay-page page-enter"><div className="module-hero essay-hero"><div className="module-icon"><FilePenLine/></div><div><span className="eyebrow">FEEDBACK YOU CAN USE</span><h1>Essay checker</h1><p>See individual errors, understand recurring patterns, and know exactly what to practice next.</p></div><div className="privacy-note"><ShieldCheck/><div><strong>Your writing stays yours</strong><span>Essays are private to your profile.</span></div></div></div><div className="essay-layout"><div><Card className="essay-editor"><label><span>Essay question <small>Optional</small></span><input value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Paste the question or task here…"/></label><label><span>Your essay</span><div className="editor-area"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Start writing or paste your essay here…"/><div><span>{text.trim()?text.trim().split(/\s+/).length:0} words</span><button onClick={()=>setText(sample)}>Use sample essay</button></div></div></label>{error&&<div className="form-error"><AlertCircle/> {error}</div>}<Button loading={loading} onClick={analyze} disabled={text.length<80}>{loading?<><LoaderCircle/>Analyzing your writing…</>:<>Analyze my essay <WandSparkles size={16}/></>}</Button></Card>{history.length>0&&<Card className="essay-history"><span className="eyebrow">SAVED ESSAYS</span><h2>Recent feedback</h2>{history.slice(0,5).map(item=><div key={item.id}><div><strong>{item.prompt}</strong><small>{new Date(item.createdAt).toLocaleDateString()}</small></div><p>{item.summary}</p><Badge tone={item.score>=7?'green':'amber'}>{item.score}/9</Badge></div>)}</Card>}</div><aside><Card className="analysis-preview"><span className="eyebrow">YOUR ANALYSIS INCLUDES</span>{[['Grammar','Articles, tenses, agreement, structure'],['Vocabulary','Word choice, range, collocations'],['Coherence','Flow, linking, paragraph logic'],['Task response','Relevance and idea development']].map(([x,y],i)=><div key={x}><span>0{i+1}</span><p><strong>{x}</strong><small>{y}</small></p><CheckCircle2/></div>)}</Card><div className="ai-disclaimer"><Sparkles/><p><strong>Built to teach, not just correct.</strong><span>MadeByAibek explains patterns and turns them into future recommendations.</span></p></div></aside></div></div>
}
