import { FormEvent, useState } from 'react'
import { ArrowLeft, CheckCircle2, KeyRound, Mail, Sparkles } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import { Button, Card } from '../components/ui'
import { api } from '../services/api'

export function PasswordResetPage(){
  const[params]=useSearchParams();const token=params.get('token');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[loading,setLoading]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');const[devToken,setDevToken]=useState('')
  const submitRequest=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{const r=await api.resetPassword(email);setMessage(r.message);setDevToken(r.devResetToken||'')}catch(err){setError(err instanceof Error?err.message:'Unable to request a reset.')}finally{setLoading(false)}}
  const submitPassword=async(e:FormEvent)=>{e.preventDefault();if(!token)return;setLoading(true);setError('');try{const r=await api.confirmPasswordReset(token,password);setMessage(r.message)}catch(err){setError(err instanceof Error?err.message:'Unable to reset password.')}finally{setLoading(false)}}
  return <div className="reset-page"><Link to="/" className="brand"><span className="brand-mark"><Sparkles size={20}/></span><span>MadeByAibek</span></Link><Card>{message?<div className="reset-success"><CheckCircle2/><h1>{token?'Password updated':'Check your email'}</h1><p>{message}</p>{devToken&&<Link className="dev-reset-link" to={`/password-reset?token=${encodeURIComponent(devToken)}`}>Open development reset link</Link>}<Link to="/login"><Button>Return to login</Button></Link></div>:<><Link to="/login" className="back-link reset-back"><ArrowLeft/>Back to login</Link><div className="reset-icon">{token?<KeyRound/>:<Mail/>}</div><span className="eyebrow">ACCOUNT RECOVERY</span><h1>{token?'Choose a new password':'Reset your password'}</h1><p>{token?'Use at least eight characters. This link expires after one hour.':'Enter the email connected to your MadeByAibek account. We’ll create a secure, time-limited reset link.'}</p><form onSubmit={token?submitPassword:submitRequest}><label>{token?'New password':'Email address'}<input type={token?'password':'email'} value={token?password:email} onChange={e=>token?setPassword(e.target.value):setEmail(e.target.value)} required minLength={token?8:undefined} placeholder={token?'At least 8 characters':'you@example.com'}/></label>{error&&<div className="form-error">{error}</div>}<Button loading={loading} type="submit">{token?'Update password':'Send reset link'}</Button></form></>}</Card></div>
}
