import { Bell, LogOut, Save, Trash2, UserRound } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { Button, Card } from '../components/ui'
import { useApp } from '../state/AppContext'

export function ProfilePage(){
  const{user,updateUser,logout,deleteAccount}=useApp();const[saved,setSaved]=useState(false);const[error,setError]=useState('');const[deleteOpen,setDeleteOpen]=useState(false);const[deletePassword,setDeletePassword]=useState('');const[deleteError,setDeleteError]=useState('');const[deleting,setDeleting]=useState(false);if(!user)return null
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');const d=new FormData(e.currentTarget);try{await updateUser({name:String(d.get('name')),dailyGoal:Number(d.get('dailyGoal')),reminderEnabled:d.get('reminderEnabled')==='on'});setSaved(true);setTimeout(()=>setSaved(false),2000)}catch(err){setError(err instanceof Error?err.message:'Unable to save changes.')}}
  const remove=async()=>{setDeleting(true);setDeleteError('');try{await deleteAccount(deletePassword)}catch(err){setDeleteError(err instanceof Error?err.message:'Unable to delete the account.');setDeleting(false)}}
  return <div className="profile-page page-enter"><div className="page-title-row"><div><span className="eyebrow">YOUR ACCOUNT</span><h1>Profile & preferences</h1><p>Manage your learning identity and daily routine.</p></div></div><div className="profile-layout"><Card><div className="profile-avatar">{user.name[0]}</div><h2>{user.name}</h2><p>{user.email}</p><span>Level {Math.floor(user.xp/100)+1} · {user.xp.toLocaleString()} XP</span></Card><div className="profile-forms"><form onSubmit={submit}><Card><h2><UserRound/> Personal details</h2><label>Display name<input name="name" defaultValue={user.name}/></label><label>Email address<input value={user.email} disabled readOnly/></label></Card><Card><h2><Bell/> Learning preferences</h2><label>Daily goal<select name="dailyGoal" defaultValue={String(user.dailyGoal??15)}><option value="10">10 minutes</option><option value="15">15 minutes</option><option value="20">20 minutes</option><option value="30">30 minutes</option></select></label><label className="toggle-row">Daily practice reminder<input name="reminderEnabled" type="checkbox" defaultChecked={user.reminderEnabled??true}/><i/></label>{error&&<div className="form-error">{error}</div>}<Button type="submit"><Save size={15}/>{saved?'Saved':'Save all changes'}</Button></Card></form><Card className="account-actions"><h2>Account actions</h2><button type="button" className="logout-action" onClick={()=>void logout()}><LogOut/>Log out</button><button type="button" className="delete-action" onClick={()=>setDeleteOpen(!deleteOpen)}><Trash2/>Delete account</button>{deleteOpen&&<div className="delete-confirm"><p>This permanently deletes your profile, essays, vocabulary, and progress. Enter your password to confirm.</p><input type="password" value={deletePassword} onChange={e=>setDeletePassword(e.target.value)} placeholder="Current password"/>{deleteError&&<div className="form-error">{deleteError}</div>}<Button variant="danger" loading={deleting} disabled={!deletePassword} onClick={remove}>Permanently delete account</Button></div>}</Card></div></div></div>
}
