import { Award, BookOpen, CalendarDays, CheckCircle2, Clock3, Download, TrendingUp, Trophy, Zap } from 'lucide-react'
import { Badge, Button, Card, ProgressBar } from '../components/ui'
import { useApp } from '../state/AppContext'

export function ProgressPage() {
  const {user}=useApp(); if(!user)return null
  const days=user.weeklyActivity??user.weeklyMinutes.map((minutes,index)=>{const date=new Date();date.setDate(date.getDate()-(6-index));return{date:date.toISOString().slice(0,10),minutes,xp:0}}); const max=Math.max(...days.map(day=>day.minutes),1)
  const weeklyTotal=days.reduce((sum,day)=>sum+day.minutes,0); const hasMeasurements=user.skills.some(skill=>skill.assessed); const nextLevel=user.level==='C1'?'C2':user.level==='B2'?'C1':user.level.startsWith('B1')?'B2':'B1'
  const exportReport=()=>{const lines=['MadeByAibek progress report',`Learner,${user.name}`,`Level,${user.level}`,`XP,${user.xp}`,'', 'Skill,Score,Change',...user.skills.map(skill=>skill.assessed?`${skill.label},${skill.score}%,${skill.delta >= 0 ? '+' : ''}${skill.delta}%`:`${skill.label},Not assessed,`),'','Recent activity',...user.activities.map(activity=>`${activity.title},${activity.score}%,${activity.date}`)];const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`madebyaibek-progress-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url)}
  return <div className="progress-page page-enter"><div className="page-title-row"><div><span className="eyebrow">YOUR LEARNING STORY</span><h1>Progress</h1><p>See what’s improving, where to focus, and how your work is adding up.</p></div><Button variant="secondary" onClick={exportReport}><Download size={15}/> Export report</Button></div>
    <div className="progress-summary"><Card className="progress-level"><div><span>Estimated level</span><strong>{user.level}</strong><Badge tone={hasMeasurements?'green':'neutral'}><TrendingUp size={12}/> {hasMeasurements?`${user.levelProgress}% measured mastery`:'Not assessed'}</Badge></div><div className="level-timeline"><div><span>{user.level}</span><small>Current estimate</small></div><i className="filled"/><div><span>{hasMeasurements?`${user.levelProgress}%`:'—'}</span><small>Skill average</small></div><i/><div className="future"><span>{nextLevel}</span><small>Next band</small></div></div></Card>{[['Total study time',`${Math.floor((user.totalMinutes??0)/60)}h ${(user.totalMinutes??0)%60}m`,Clock3],['Exercises completed',String(user.totalAttempts??user.activities.length),CheckCircle2],['XP earned',user.xp.toLocaleString(),Zap]].map((item)=>{const[x,v,Icon]=item as [string,string,typeof Clock3];return <Card className="summary-stat" key={x}><Icon/><span>{x}</span><strong>{v}</strong><small>All time</small></Card>})}</div>
    <div className="analytics-grid"><Card className="weekly-chart"><div className="chart-head"><div><span className="eyebrow">ACTIVITY</span><h2>Learning time</h2></div><Badge><CalendarDays size={12}/> Last 7 days</Badge></div><div className="bar-chart"><div className="y-axis"><span>{max}</span><span>{Math.round(max*2/3)}</span><span>{Math.round(max/3)}</span><span>0</span></div><div className="bars">{days.map((day,i)=><div key={day.date}><span className={i===6?'active':''} style={{height:`${day.minutes/max*100}%`}}><em>{day.minutes}</em></span><small>{new Date(`${day.date}T12:00:00`).toLocaleDateString('en-US',{weekday:'short'})}</small></div>)}</div></div><div className="chart-footer"><strong>{weeklyTotal} minutes</strong><span>Recorded session time</span></div></Card><Card className="consistency"><span className="eyebrow">CONSISTENCY</span><h2>{user.streak}-day streak</h2><div className="streak-big">{user.streak}<small>days</small></div><p>Keep practicing each day to extend your current learning streak.</p><ProgressBar value={Math.min(100,user.streak/12*100)}/><div><span>Current</span><strong>Next milestone: 12 days</strong></div></Card></div>
    <div className="skills-analytics"><div><span className="eyebrow">SKILL DEVELOPMENT</span><h2>Performance by skill</h2></div><Card>{user.skills.map(s=><div className="skill-analytics-row" key={s.key}><div><strong>{s.label}</strong><small>{!s.assessed?'Not assessed':s.score>=75?'Strong':s.score>=60?'Developing':'Focus area'}</small></div><div className="historic-bars"><span className="now" style={{width:`${s.assessed?s.score:0}%`}}/></div><strong>{s.assessed?`${s.score}%`:'—'}</strong><Badge tone={s.delta>0?'green':'neutral'}>{s.assessed&&s.attempts?`${s.delta>=0?'+':''}${s.delta}%`:'No change'}</Badge></div>)}</Card></div>
    <div className="achievement-section"><div><span className="eyebrow">MILESTONES</span><h2>Achievements</h2></div><div className="achievement-grid">{(user.achievements??[]).map((achievement,i)=>{const Icon=[Trophy,BookOpen,Award,Trophy][i%4];return <Card key={achievement.id} className={achievement.earned?'earned':'locked'}><div className={`achievement-icon ac-${i}`}><Icon/></div><div><strong>{achievement.title}</strong><span>{achievement.description}</span></div>{achievement.earned?<CheckCircle2/>:<span className="achievement-status">In progress</span>}</Card>})}</div></div>
  </div>
}
