import { ArrowRight, BookMarked, Check, ChevronLeft, ChevronRight, Clock3, RotateCcw, Sparkles, Volume2, X } from 'lucide-react'
import { useState } from 'react'
import { Badge, Button, Card, ProgressBar } from '../components/ui'
import { vocabulary, vocabularyQuestions } from '../data/seed'
import { useApp } from '../state/AppContext'
import { ExercisePlayer } from '../components/ExercisePlayer'

export function VocabularyPage() {
  const { user, updateVocabulary } = useApp(); const [index,setIndex]=useState(0); const [flipped,setFlipped]=useState(false); const [practicing,setPracticing]=useState(false); const word=vocabulary[index]; if(!user)return null
  const reviewed=Object.values(user.vocabularyProgress??{}); const due=reviewed.filter(item=>item.due).length; const recall=reviewed.length?`${Math.round(reviewed.reduce((sum,item)=>sum+item.mastery,0)/reviewed.length)}%`:'—'
  const mark=async(known:boolean)=>{ await updateVocabulary(word.id,known?'known':'weak'); setFlipped(false); setIndex((index+1)%vocabulary.length) }
  const pronounce=()=>{if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(word.word);utterance.lang='en-GB';window.speechSynthesis.speak(utterance)}
  if(practicing)return <ExercisePlayer title="Academic vocabulary practice" questions={vocabularyQuestions} skill="vocabulary" onExit={()=>setPracticing(false)}/>
  return <div className="vocab-page page-enter"><div className="page-title-row"><div><span className="eyebrow">BUILD USEFUL RANGE</span><h1>Vocabulary</h1><p>Learn words in context, then review them exactly when they need attention.</p></div><div className="page-actions"><Button variant="secondary" onClick={()=>{const next=vocabulary.findIndex(item=>user.weakWords.includes(item.id));setIndex(next>=0?next:0);setFlipped(false)}}><RotateCcw size={16}/> Review weak words</Button><Button onClick={()=>setPracticing(true)}>Practice set <ArrowRight size={16}/></Button></div></div>
    <div className="vocab-stats">{[['Words learned',String(user.knownWords.length),'Saved to your profile'],['Due for review',String(due),'Scheduled for today'],['Current set','Academic 08','B2 · adaptive'],['Recall strength',recall,reviewed.length?'Based on your reviews':'No reviews yet']].map(([a,b,c],i)=><Card key={a}><div className={`tiny-icon vi-${i}`}><BookMarked/></div><span>{a}</span><strong>{b}</strong><small>{c}</small></Card>)}</div>
    <div className="vocab-workspace"><div className="review-queue"><div><span className="eyebrow">Today’s review</span><h2>Academic words</h2><p>{index+1} of {vocabulary.length}</p></div>{vocabulary.map((w,i)=>{const saved=user.vocabularyProgress?.[w.id];return <button key={w.id} className={i===index?'active':''} onClick={()=>{setIndex(i);setFlipped(false)}}><span>{saved?.status==='known'?<Check/>:i+1}</span><div><strong>{w.word}</strong><small>{saved?.due?'Due for review':saved?`${w.level} · ${saved.mastery}% mastery`:`${w.level} · Not reviewed`}</small></div><ProgressBar value={saved?.mastery??0}/></button>})}</div>
      <div className="word-study"><div className="word-card"><div className="word-card-top"><Badge tone="blue">{word.level}</Badge><button onClick={pronounce} aria-label={`Play pronunciation of ${word.word}`}><Volume2/></button></div><span className="word-count">WORD {index+1} OF {vocabulary.length}</span><h2>{word.word}</h2><span className="pronunciation">{word.pronunciation}</span><p className="definition">{word.definition}</p><blockquote>“{word.example}”</blockquote>{flipped?<div className="word-details"><div><span>Synonyms</span><p>{word.synonyms.map(x=><Badge key={x}>{x}</Badge>)}</p>{word.antonyms?.length?<><span>Antonyms</span><p>{word.antonyms.map(x=><Badge key={x} tone="amber">{x}</Badge>)}</p></>:null}</div><div><span>Common collocations</span><p>{word.collocations.map(x=><Badge key={x} tone="green">{x}</Badge>)}</p></div><div><span>Word family</span><p>{word.family.join(' · ')}</p></div></div>:<button className="reveal" onClick={()=>setFlipped(true)}>Show word connections <ArrowRight/></button>}</div>
        <div className="memory-actions"><button onClick={()=>mark(false)}><X/><span><strong>Needs review</strong><small>I’m not sure yet</small></span></button><button onClick={()=>mark(true)}><Check/><span><strong>I know this</strong><small>Move to next word</small></span></button></div><div className="card-nav"><button onClick={()=>setIndex(Math.max(0,index-1))} disabled={!index}><ChevronLeft/> Previous</button><span><Clock3/> Next review adapts to your answer</span><button onClick={()=>setIndex((index+1)%vocabulary.length)}>Skip <ChevronRight/></button></div>
      </div></div>
  </div>
}
