import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App'
import { AppProvider } from './state/AppContext'
import './styles.css'
import './auth.css'
import './app.css'
import './pages.css'
import './modules.css'
import './insights.css'
import './responsive.css'
import './diagnostic.css'
import './fullstack.css'
import './reset-extra.css'
import './interactive.css'
import './page-actions.css'
import './achievements.css'
import './empty.css'
import './fatal.css'
import './profile-actions.css'
import './mainideas-extra.css'
import './search.css'
import './lesson-responsive.css'
import './integrated-summary.css'
import './theme.css'
import { ErrorBoundary } from './components/ErrorBoundary'

createRoot(document.getElementById('root')!).render(<StrictMode><BrowserRouter><ErrorBoundary><AppProvider><App/></AppProvider></ErrorBoundary></BrowserRouter></StrictMode>)
